# Generated by Django 5.2.6 on 2025-09-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_worklog"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="estimated_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated total hours needed",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="progress",
            field=models.IntegerField(
                default=0, help_text="Project progress percentage (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
