# Generated by Django 5.2.6 on 2025-09-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_estimated_hours_project_progress_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="estimated_hours",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="project",
            name="progress",
        ),
        migrations.RemoveField(
            model_name="project",
            name="project_status",
        ),
        migrations.RemoveField(
            model_name="project",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="status",
        ),
        migrations.RemoveField(
            model_name="project",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="project",
            name="work_location",
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                max_length=100, verbose_name="Category of the Project"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="company",
            field=models.CharField(
                max_length=255, verbose_name="Company name allocating Project"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="completion_date",
            field=models.DateField(verbose_name="Date of tentative Completion"),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(verbose_name="Description of Project"),
        ),
        migrations.AlterField(
            model_name="project",
            name="location",
            field=models.CharField(
                max_length=255, verbose_name="Location of installation"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name of the Project"),
        ),
        migrations.AlterField(
            model_name="project",
            name="tender_award_date",
            field=models.DateField(verbose_name="Date on which Tender awarded"),
        ),
    ]
