# Generated by Django 5.2.6 on 2025-09-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_remove_project_estimated_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="submission_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
