# Generated by Django 5.2.6 on 2025-09-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_project_submission_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="client_confirmed_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="client_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="client_feedback",
            field=models.TextField(blank=True, null=True),
        ),
    ]
